service: GoAthenaDriver

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  memorySize: 1024
  timeout: 30

  # Role Statements
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "athena:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.S3.bucketName}"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.S3.bucketName}/*"
    - Effect: "Allow"
      Action:
        - "glue:*"
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  getState:
    handler: bin/getState
    # Define function environment variables here
    environment:
      ACCOUNT: mtdatadev
      REGION: ap-southeast-2
      BUCKET: s3://${self:custom.S3.bucketName}/
    # API Gateway Definition
    events:
      - http:
          path: stateCount
          method: get
          request:
            parameters:
              querystrings: state

custom:
  S3:
    bucketName: brads-playground

   